#!/bin/bash

args=("$@")

while test $# -gt 0
do
    case "$1" in
        --version) pylint --version; exit
            ;;
        *)
            ;;
    esac
    shift
done

pyflaked=`pyflakes test.py | sed -e 's/:\([0-9][0-9]*\):/:\1:0:C: [pyflakes]/'`
echo "${pyflaked}" > /home/max/test.txt
echo "${pyflaked}"
if [ -z "${pyflaked}" ]
then
  pylint "${args[@]}" | tail -n +2
fi
